---
- name: 'update and upgrade repos'
  apt:
    upgrade: dist
    update_cache: true
    force: yes
  no_log: true

- name: 'install useful packages'
  apt:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - emacs
      - tmux
      - git
      - cowsay
