version: '3.3'
services:
  db:
    build:
      context: ../common/db/
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ../common/db/.env
    image: app
    ports:
      - 5000:9292
    depends_on:
      - db
    command: ["./wait-for-it.sh", "-t", "0", "db:3306", "--", "bundle", "exec", "rackup", "-o", "0.0.0.0"]
