version: '3.3'
services:
  db:
    build:
      context: ./common/db/
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always

  python-app:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: app
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./:/app
    command: ["sleep", "360000"]
    env_file:
      - ./common/db/.env

  node-app:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: node
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./:/app
    command: ["sleep", "360000"]
    env_file:
      - ./common/db/.env


  ruby-app:
    build:
      context: .
      dockerfile: Dockerfile-ruby
    image: ruby
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./:/app
    command: ["sleep", "360000"]
    env_file:
      - ./common/db/.env